//! The browser entry point.
//!
//! This is a plain `cdylib` with a hand-written C ABI rather than anything
//! generated by a bindings tool: the whole build is `cargo build --target
//! wasm32-unknown-unknown`, with no npm, no version-matched CLI, and nothing
//! that can drift out of step with the compiler.
//!
//! Every export is named `zelduh_*` on the wasm side. The prefix is not
//! decoration: a plain `free` or `alloc` would collide with the C library's
//! symbols of the same name in any native build of this crate.
//!
//! The interface is deliberately narrow. Everything crosses the boundary as
//! integers or as bytes in the module's own memory:
//!
//! * JavaScript owns input, files, audio and the canvas.
//! * Rust owns the world, the pixels and every decision that affects state.
//!
//! That split is what will make multiplayer work: the browser is a terminal
//! for a simulation that only ever advances through [`step`].

use std::cell::RefCell;

use zelduh_assets::pack::AssetPack;
use zelduh_assets::{builtin, FileKind};
use zelduh_core::event::Event;
use zelduh_core::World;
use zelduh_gen::Config;
use zelduh_render::Framebuffer;

/// Everything the page is holding on to.
struct Game {
    world: World,
    pack: AssetPack,
    fb: Framebuffer,
    /// Sound and shake events from the last step, as bytes for the audio code.
    events: Vec<u8>,
    /// Text describing the last file that was loaded.
    report: String,
    /// Scratch buffer for bytes handed in from JavaScript.
    incoming: Vec<u8>,
}

thread_local! {
    static GAME: RefCell<Option<Game>> = const { RefCell::new(None) };
}

/// Runs `f` with the game, or returns `default` when there is no game yet.
fn with_game<T>(default: T, f: impl FnOnce(&mut Game) -> T) -> T {
    GAME.with(|g| match g.borrow_mut().as_mut() {
        Some(game) => f(game),
        None => default,
    })
}

// ----- memory ------------------------------------------------------------

/// Reserves `len` bytes for JavaScript to write into. Pair with [`free`].
///
/// # Safety
/// The returned pointer is valid for `len` bytes until [`free`] is called with
/// the same pointer and length.
#[export_name = "zelduh_alloc"]
pub extern "C" fn alloc(len: usize) -> *mut u8 {
    let mut buf = Vec::with_capacity(len);
    let ptr = buf.as_mut_ptr();
    std::mem::forget(buf);
    ptr
}

/// Releases memory from [`alloc`].
///
/// # Safety
/// `ptr` must have come from [`alloc`] with the same `len`, and must not be
/// used afterwards.
#[export_name = "zelduh_free"]
pub unsafe extern "C" fn free(ptr: *mut u8, len: usize) {
    if !ptr.is_null() && len > 0 {
        drop(Vec::from_raw_parts(ptr, 0, len));
    }
}

// ----- lifecycle ---------------------------------------------------------

/// Creates a world from a seed. Any previous world is discarded, except that
/// a loaded asset pack is kept so a new seed does not throw away the player's
/// graphics.
#[export_name = "zelduh_new_game"]
pub extern "C" fn new_game(seed_lo: u32, seed_hi: u32, players: u32) -> u32 {
    let seed = ((seed_hi as u64) << 32) | seed_lo as u64;
    let players = players.clamp(1, 8) as usize;
    let world = zelduh_gen::new_world(Config::from_seed(seed), players);
    GAME.with(|g| {
        let mut slot = g.borrow_mut();
        let pack = slot
            .as_ref()
            .map(|old| old.pack.clone())
            .unwrap_or_else(builtin::pack);
        *slot = Some(Game {
            world,
            pack,
            fb: Framebuffer::new(),
            events: Vec::new(),
            report: String::new(),
            incoming: Vec::new(),
        });
    });
    1
}

/// Brings a player into the world.
#[export_name = "zelduh_join"]
pub extern "C" fn join(player: u32) -> u32 {
    with_game(0, |g| u32::from(g.world.join(player as usize)))
}

/// Removes a player from the world.
#[export_name = "zelduh_leave"]
pub extern "C" fn leave(player: u32) {
    with_game((), |g| g.world.leave(player as usize));
}

/// Sets the buttons held by a player for the next step.
#[export_name = "zelduh_set_input"]
pub extern "C" fn set_input(player: u32, buttons: u32) {
    with_game((), |g| {
        g.world.set_input(player as usize, buttons as u16);
    });
}

/// Advances the world by one frame and collects its events.
#[export_name = "zelduh_step"]
pub extern "C" fn step() {
    with_game((), |g| {
        g.world.step();
        g.events.clear();
        for e in g.world.events.iter() {
            match e {
                Event::Sound(s) => {
                    g.events.push(1);
                    g.events.push(*s as u8);
                }
                Event::Shake { frames } => {
                    g.events.push(2);
                    g.events.push(*frames);
                }
                Event::PlayerHurt { player, .. } => {
                    g.events.push(3);
                    g.events.push(*player);
                }
                Event::PlayerDied { player } => {
                    g.events.push(4);
                    g.events.push(*player);
                }
                Event::LevelChanged { player, level } => {
                    g.events.push(5);
                    g.events.push(*player);
                    g.events.push(*level as u8);
                }
                Event::BossDefeated { .. } => {
                    g.events.push(6);
                    g.events.push(0);
                }
                _ => {}
            }
        }
        // Screen shake is a presentation effect, but it is driven from the
        // simulation's events so every viewer sees it at the same moment.
        let shakes: Vec<u8> = g
            .world
            .events
            .iter()
            .filter_map(|e| match e {
                Event::Shake { frames } => Some(*frames),
                _ => None,
            })
            .collect();
        if let Some(max) = shakes.into_iter().max() {
            for p in g.world.players.iter_mut() {
                p.camera.shake = p.camera.shake.max(max);
            }
        }
    });
}

/// Draws the world from a player's point of view into the framebuffer.
#[export_name = "zelduh_render"]
pub extern "C" fn render(player: u32) {
    with_game((), |g| {
        let (world, pack, fb) = (&g.world, &g.pack, &mut g.fb);
        zelduh_render::render(fb, world, pack, player as usize);
    });
}

/// Pointer to the framebuffer, as `width * height` RGBA pixels.
#[export_name = "zelduh_framebuffer"]
pub extern "C" fn framebuffer() -> *const u8 {
    with_game(std::ptr::null(), |g| g.fb.as_bytes().as_ptr())
}

/// Length of the framebuffer in bytes.
#[export_name = "zelduh_framebuffer_len"]
pub extern "C" fn framebuffer_len() -> usize {
    with_game(0, |g| g.fb.as_bytes().len())
}

/// Screen width in pixels.
#[export_name = "zelduh_screen_width"]
pub extern "C" fn screen_width() -> u32 {
    zelduh_core::level::SCREEN_W as u32
}

/// Screen height in pixels.
#[export_name = "zelduh_screen_height"]
pub extern "C" fn screen_height() -> u32 {
    zelduh_core::level::SCREEN_H as u32
}

// ----- events and status -------------------------------------------------

/// Pointer to this frame's events, as pairs or triples of bytes.
#[export_name = "zelduh_events"]
pub extern "C" fn events() -> *const u8 {
    with_game(std::ptr::null(), |g| g.events.as_ptr())
}

/// Length of this frame's event bytes.
#[export_name = "zelduh_events_len"]
pub extern "C" fn events_len() -> usize {
    with_game(0, |g| g.events.len())
}

/// Frames simulated so far.
#[export_name = "zelduh_frame"]
pub extern "C" fn frame() -> u32 {
    with_game(0, |g| g.world.frame as u32)
}

/// Number of live entities, for the debug readout.
#[export_name = "zelduh_entity_count"]
pub extern "C" fn entity_count() -> u32 {
    with_game(0, |g| g.world.entities.len() as u32)
}

/// Which level a player is on.
#[export_name = "zelduh_player_level"]
pub extern "C" fn player_level(player: u32) -> u32 {
    with_game(0, |g| {
        g.world
            .players
            .get(player as usize)
            .map(|p| p.level as u32)
            .unwrap_or(0)
    })
}

/// A player's health in quarter hearts, or -1 when they are not in the world.
#[export_name = "zelduh_player_health"]
pub extern "C" fn player_health(player: u32) -> i32 {
    with_game(-1, |g| {
        g.world
            .player_entity(player as usize)
            .map(|e| e.hp as i32)
            .unwrap_or(-1)
    })
}

/// How many rupees a player is carrying.
#[export_name = "zelduh_player_rupees"]
pub extern "C" fn player_rupees(player: u32) -> u32 {
    with_game(0, |g| {
        g.world
            .players
            .get(player as usize)
            .map(|p| p.inv.rupees as u32)
            .unwrap_or(0)
    })
}

/// How many monsters a player has felled.
#[export_name = "zelduh_player_kills"]
pub extern "C" fn player_kills(player: u32) -> u32 {
    with_game(0, |g| {
        g.world
            .players
            .get(player as usize)
            .map(|p| p.kills)
            .unwrap_or(0)
    })
}

// ----- assets ------------------------------------------------------------

/// Hands a file to the engine.
///
/// `kind` is 0 to sniff the type, 1 ROM, 2 raw tiles, 3 BMP, 4 RGBA, 5 profile.
/// For RGBA, `width` and `height` describe the image. The bytes are read from
/// `ptr`, which stays owned by the caller.
///
/// Returns the number of tiles imported, or -1 when the file was not
/// understood. [`report`] describes what happened either way.
///
/// # Safety
/// `ptr` must point to `len` readable bytes.
#[export_name = "zelduh_load_asset"]
pub unsafe extern "C" fn load_asset(
    ptr: *const u8,
    len: usize,
    kind: u32,
    width: u32,
    height: u32,
) -> i32 {
    if ptr.is_null() {
        return -1;
    }
    let data = std::slice::from_raw_parts(ptr, len);
    with_game(-1, |g| {
        g.incoming.clear();
        g.incoming.extend_from_slice(data);
        let name = "dropped file";
        let kind = match kind {
            1 => Some(FileKind::Rom),
            2 => Some(FileKind::RawTiles),
            3 => Some(FileKind::Bmp),
            4 => Some(FileKind::Rgba {
                width: width as usize,
                height: height as usize,
            }),
            5 => Some(FileKind::Profile),
            _ => zelduh_assets::sniff(name, &g.incoming),
        };
        let Some(kind) = kind else {
            g.report = "could not tell what sort of file that is".to_string();
            return -1;
        };
        let bytes = std::mem::take(&mut g.incoming);
        let r = zelduh_assets::load(&mut g.pack, name, &bytes, kind);
        g.incoming = bytes;
        g.report = if r.warnings.is_empty() {
            r.detail.clone()
        } else {
            format!("{} ({})", r.detail, r.warnings.join("; "))
        };
        r.tiles_imported as i32
    })
}

/// Throws away any imported graphics and goes back to the built-in art.
#[export_name = "zelduh_reset_assets"]
pub extern "C" fn reset_assets() {
    with_game((), |g| {
        g.pack = builtin::pack();
        g.report = "using the built-in art".to_string();
    });
}

/// Pointer to the description of the last file that was loaded, as UTF-8.
#[export_name = "zelduh_report"]
pub extern "C" fn report() -> *const u8 {
    with_game(std::ptr::null(), |g| g.report.as_ptr())
}

/// Length in bytes of the text from [`report`].
#[export_name = "zelduh_report_len"]
pub extern "C" fn report_len() -> usize {
    with_game(0, |g| g.report.len())
}

/// How many 8x8 tiles the current asset pack holds.
#[export_name = "zelduh_tile_count"]
pub extern "C" fn tile_count() -> u32 {
    with_game(0, |g| g.pack.tile_count() as u32)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_game_can_be_created_stepped_and_drawn() {
        assert_eq!(new_game(1234, 0, 2), 1);
        assert_eq!(join(0), 1);
        for _ in 0..30 {
            set_input(0, zelduh_core::button::RIGHT as u32);
            step();
        }
        assert_eq!(frame(), 30);
        render(0);
        assert_eq!(
            framebuffer_len(),
            (screen_width() * screen_height() * 4) as usize
        );
        assert!(player_health(0) > 0);
    }

    #[test]
    fn calls_before_the_game_exists_are_harmless() {
        GAME.with(|g| *g.borrow_mut() = None);
        step();
        render(0);
        assert_eq!(framebuffer_len(), 0);
        assert_eq!(player_health(0), -1);
        assert!(framebuffer().is_null());
    }

    #[test]
    fn a_new_seed_keeps_the_loaded_graphics() {
        new_game(1, 0, 1);
        let tiles = vec![0xffu8; 64 * 16];
        let imported = unsafe { load_asset(tiles.as_ptr(), tiles.len(), 2, 0, 0) };
        assert_eq!(imported, 64);
        let before = tile_count();
        new_game(2, 0, 1);
        assert_eq!(tile_count(), before, "the pack should have survived");
    }

    #[test]
    fn a_file_that_makes_no_sense_is_reported_not_crashed() {
        new_game(1, 0, 1);
        let junk = [0u8; 3];
        let r = unsafe { load_asset(junk.as_ptr(), junk.len(), 0, 0, 0) };
        assert_eq!(r, -1);
        assert!(report_len() > 0);
    }

    #[test]
    fn events_are_emitted_as_bytes() {
        new_game(7, 0, 1);
        join(0);
        // Swinging the sword always makes a noise.
        set_input(0, zelduh_core::button::A as u32);
        step();
        assert!(events_len() >= 2);
        let ptr = events();
        let bytes = unsafe { std::slice::from_raw_parts(ptr, events_len()) };
        assert_eq!(bytes[0], 1, "the first event should be a sound");
    }

    #[test]
    fn allocation_roundtrips() {
        let p = alloc(64);
        assert!(!p.is_null());
        unsafe {
            std::ptr::write_bytes(p, 7, 64);
            assert_eq!(*p, 7);
            free(p, 64);
        }
    }
}
